# Build settings
gems:
  - jekyll-seo-tag
  - jekyll-seo
  - jemoji
  - jekyll-paginate

# Site settings
title: LYNGO
description: > # this means to ignore newlines until "email:"
   Lyngo app is the the best way to learn a new language using video content that you already know and love!

email: lyngoteam@gmail.com
#blog logo
logo: "/assets/images/lyngo-icon.png"
# blog cover
cover: "/assets/images/lyngo-footer.png"

name: 'Lyngo Team'
author: 'Lyngo Team'
author_image: "/assets/images/author.jpg"

paginate:	6
paginate_path: "/blog/index.html"

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@kh4ri'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/kh4ri
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/khari1090
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
